import assert from "node:assert/strict";
import test from "node:test";

import { checksumContent } from "./checksum.ts";
import { classifyProject } from "./classify.ts";
import type { DesignSystemManifest } from "./types.ts";

function manifest(files: DesignSystemManifest["files"]): DesignSystemManifest {
  return {
    schemaVersion: 1,
    engineVersion: "1.0.0",
    templateId: "storybook-vite",
    createdWith: "1.0.0",
    appliedMigrations: [],
    files,
  };
}

test("unmodified: current checksum matches manifest, including a reverted file", () => {
  const original = checksumContent("export const Button = () => null;\n");
  const result = classifyProject({
    manifest: manifest({ "src/Button.tsx": { sha256: original } }),
    currentChecksums: new Map([["src/Button.tsx", original]]),
    incomingPaths: new Set(["src/Button.tsx"]),
    generatedPaths: new Set(),
  });
  assert.deepEqual(result, [{ path: "src/Button.tsx", category: "unmodified" }]);
});

test("conflicted: current checksum differs from manifest", () => {
  const result = classifyProject({
    manifest: manifest({ "src/Button.tsx": { sha256: checksumContent("old\n") } }),
    currentChecksums: new Map([["src/Button.tsx", checksumContent("edited\n")]]),
    incomingPaths: new Set(["src/Button.tsx"]),
    generatedPaths: new Set(),
  });
  assert.deepEqual(result, [{ path: "src/Button.tsx", category: "conflicted" }]);
});

test("new: shipped by the incoming template but absent locally, whether or not the manifest tracked it", () => {
  const brandNew = classifyProject({
    manifest: manifest({}),
    currentChecksums: new Map(),
    incomingPaths: new Set(["src/NewWidget.tsx"]),
    generatedPaths: new Set(),
  });
  assert.deepEqual(brandNew, [{ path: "src/NewWidget.tsx", category: "new" }]);

  const deletedLocally = classifyProject({
    manifest: manifest({ "src/Removed.tsx": { sha256: checksumContent("gone\n") } }),
    currentChecksums: new Map(),
    incomingPaths: new Set(["src/Removed.tsx"]),
    generatedPaths: new Set(),
  });
  assert.deepEqual(deletedLocally, [{ path: "src/Removed.tsx", category: "new" }]);
});

test("user-created: exists locally, untracked, and not shipped by the template", () => {
  const result = classifyProject({
    manifest: manifest({}),
    currentChecksums: new Map([["src/Custom.tsx", checksumContent("custom\n")]]),
    incomingPaths: new Set(),
    generatedPaths: new Set(),
  });
  assert.deepEqual(result, [{ path: "src/Custom.tsx", category: "user-created" }]);
});

test("conflicted: a user-created file collides with a path the new template now ships", () => {
  const result = classifyProject({
    manifest: manifest({}),
    currentChecksums: new Map([["src/Collide.tsx", checksumContent("custom\n")]]),
    incomingPaths: new Set(["src/Collide.tsx"]),
    generatedPaths: new Set(),
  });
  assert.deepEqual(result, [{ path: "src/Collide.tsx", category: "conflicted" }]);
});

test("generated: always generated regardless of checksum drift, even when ds generate changed the barrel", () => {
  const result = classifyProject({
    manifest: manifest({ "src/components/atoms/index.ts": { sha256: checksumContent("old\n") } }),
    currentChecksums: new Map([["src/components/atoms/index.ts", checksumContent("regenerated by ds generate\n")]]),
    incomingPaths: new Set(["src/components/atoms/index.ts"]),
    generatedPaths: new Set(["src/components/atoms/index.ts"]),
  });
  assert.deepEqual(result, [{ path: "src/components/atoms/index.ts", category: "generated" }]);
});

test("adopt-merged: reported and takes precedence over every other check, including generated", () => {
  const result = classifyProject({
    manifest: manifest({ "src/styles/tokens.css": { mark: "merged" } }),
    currentChecksums: new Map([["src/styles/tokens.css", checksumContent("merged\n")]]),
    incomingPaths: new Set(),
    generatedPaths: new Set(["src/styles/tokens.css"]),
  });
  assert.deepEqual(result, [{ path: "src/styles/tokens.css", category: "adopt-merged" }]);
});

test("no longer shipped: a manifest-tracked file the new template stopped shipping is left unclassified", () => {
  const result = classifyProject({
    manifest: manifest({ "src/Retired.tsx": { sha256: checksumContent("old\n") } }),
    currentChecksums: new Map([["src/Retired.tsx", checksumContent("old\n")]]),
    incomingPaths: new Set(),
    generatedPaths: new Set(),
  });
  assert.deepEqual(result, []);
});
